# Generated by Django 4.0.4 on 2022-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('gpa', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('level', models.PositiveIntegerField(choices=[(1, 'Level-1'), (2, 'Level-2'), (3, 'Level-3'), (4, 'Level-4')])),
                ('active', models.BooleanField()),
                ('department', models.CharField(choices=[('IT', 'IT'), ('CS', 'CS'), ('AI', 'AI'), ('DS', 'DS'), ('IS', 'IS')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
