# Generated by Django 4.0.4 on 2022-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsaffair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.PositiveIntegerField(default=20200503),
            preserve_default=False,
        ),
    ]
