# Generated by Django 4.0.4 on 2022-05-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsaffair', '0004_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=8),
        ),
    ]
